### ISSUE TITLE
Aframe?

### ISSUE THREAD

**Issue by janpio** [JamesMilnerUK/THREEAR#20]
A lot of the popularity of AR.js comes from being compatible with Aframe, which is even simpler than using three.js. Are you planning / thinking about supporting this as well?

**Comment by JamesMilnerUK** [comment]
@janpio I did consider it, but I think actually sticking to one target library helps keep things focused. AR.js is a big repository that covers a lot of ground and I think that by keeping to one library this will hopefully be easier to maintain and develop. 

I have a lot of respect for Aframe and totally agree it is simpler to use, but it also (to my understanding) isn't quite as flexible and as such that's why I focused efforts on Three.js.

**Comment by janpio** [comment]
That is of course a valid decision. 

Maybe it will be possible to add an Aframe layer on top when the Three.js support is done.

(Anecdotal data: Most of the AR.js usage. at least according to Stack Overflow questions and issues created is via Aframe)

**Comment by JamesMilnerUK** [comment]
@janpio going to close this now, but just wanted to say thanks for raising it!

**Comment by kalwalt** [comment]
Sorry to re-open this but i think that `Aframe + TREEAR` it will be a nice feature indeed. Maybe a parallel project?
