### ISSUE TITLE
THREEAR.js (2mb)

### ISSUE THREAD

**Issue by stephanedemotte** [JamesMilnerUK/THREEAR#61]
Hello 

THREEAR.js really is 2mb ?

https://github.com/JamesMilnerUK/THREEAR/blob/master/dist/THREEAR.js

It's so big, webpack freeze on build.

Thanks

**Comment by 0b01001101** [comment]
If you use gzip compression you can reduce the size dramatically: gzip - [uncompressed]
THREEJS: 353kB - [550kB]
THREEAR: 343kB - [1390kB]
SUM: 700kB - [1940kB]

But an WebAssembly version of the libary would also be great.

**Comment by JamesMilnerUK** [comment]
@stephanedemotte unfortunately so. This is all almost exclusively because of the artoolkit Emscripten build: https://github.com/JamesMilnerUK/THREEAR/blob/master/src/artoolkit/lib/arjs.artoolkit.debug.js (3mb before minification). There might be a way to compile a smaller version but I really haven't tried or have time to do so. There is an open issue at #22 if anyone is interested. For now I will close this!

**Comment by JamesMilnerUK** [comment]
I actually figured out we include the `debug` version of `artoolkitjs`. I used the `min` version (https://github.com/jeromeetienne/AR.js/blob/master/three.js/vendor/jsartoolkit5/build/artoolkit.min.js) and we're down to `763 KiB`. That's still obivously enoromous but much better than 2mb and is under ar.js which comes in at  929 KB.
